apiVersion: v1
kind: Service
metadata:
  name: insurance-app-service
  labels:
    app: insurance-app
spec:
  type: NodePort
  selector:
    app: insurance-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
